spring:
  application: fitness-club

  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true
server:
  port: 9777
logging:
  level:
    ROOT: ERROR
  file:
    name: "fitness_club.log"

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        slidingWindowSize: 3
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 10
        failureRateThreshold: 3
        waitDurationInOpenState: 2s
        minimumNumberOfCalls: 3
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches-cache"
  health:
    circuitbreakers:
      enabled: true
    diskspace:
      enabled: true
    defaults:
      enabled: true