spring:
  application: fitness-club-management

  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always
#      schema-locations: schema.sql
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true
server:
  port: 8080
logging:
  level:
    ROOT: ERROR
  file:
    name: "fitness_club-manager.log"

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches-cache"