create table if not exists owners (
    id integer generated by default as identity,
    full_name varchar(255),
    primary key (id)
);

create table if not exists trainers (
    id integer generated by default as identity,
    full_name varchar(255),
    age integer,
    сoaching_experience integer,
    primary key (id)
);

create table if not exists visitors (
    id integer generated by default as identity,
    title varchar(255),
    author_id bigint references authors (id) on delete cascade,
    genre_id bigint references genres(id) on delete cascade,
    primary key (id)
);

create table if not exists workouts (
    id integer generated by default as identity,
    workout_name varchar(255),
    cost_of_workout integer,
    primary key (id)
);

