create table if not exists owners (
    id integer generated by default as identity,
    full_name varchar(255),
    primary key (id)
);

create table if not exists trainers (
    id integer generated by default as identity,
    full_name varchar(255),
    age integer,
    сoaching_experience integer,
    primary key (id)
);

create table if not exists visitors (
    id integer generated by default as identity,
    fullName varchar(255),
    age integer
    primary key (id)
);

create table if not exists cards (
    id integer generated by default as identity,
    trainerName varchar(255),
    workoutName varchar(255),
    numberOfWorkouts integer,
    primary key (id)
);

create table if not exists workouts (
    id integer generated by default as identity,
    workout_name varchar(255),
    cost_of_workout integer,
    primary key (id)
);

